### ISSUE TITLE
Is this file required to be in the repo?

### ISSUE THREAD

**Issue by jjrodrig** [lamassuiot/lamassu-ui#3]
A final env-config.js is provided when building the Docker image. This file seems to be required only for dev purpouses. Can we remove this from repo?

https://github.com/lamassuiot/lamassu-ui/blob/e7ab5f67cd25dec16ad1840098beb7def1dcfe14/public/env-config.js#L1

**Comment by haritzsaiz** [comment]
Yes I had the same thought while reviewing the #9 issue. I'll add it to the .gitignore

**Comment by haritzsaiz** [comment]
this has been fixed in pr #9 and has been merged into develop
